#!/usr/bin/env python3
"""Generate SEO structured data (JSON-LD), sitemap.xml, and robots.txt for
Central Lake County Fun, and inject the JSON-LD into index.html.

- WebSite + SearchAction (sitelinks searchbox)
- Organization
- ItemList of upcoming Event objects (Google events rich results)

Idempotent: replaces the block between the SEO-JSONLD markers on each run.
Run from the repo root:  python3 tools/build_seo.py
"""
import csv, json, datetime, re, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB = os.path.dirname(REPO)
SHAREABLE = os.path.join(LIB, "library_events_2026_summer_SHAREABLE.csv")
INDEX = os.path.join(REPO, "index.html")
SITE = "https://julianamapper.github.io/central-lake-county-fun/"

TODAY = datetime.date(2026, 6, 13)          # "now" for this build
WINDOW_DAYS = 30                            # upcoming events to emit as Event schema
TZ = "-05:00"                               # America/Chicago (CDT) in summer

MARK_START = "<!-- SEO-JSONLD:START (generated by tools/build_seo.py — do not hand-edit) -->"
MARK_END = "<!-- SEO-JSONLD:END -->"

EXCLUDE_ORGS = {"Wheaton Public Library", "Glen Ellyn Public Library"}

MONTHS = None  # not needed; dates already ISO


def parse_start(date_iso, time_str):
    """Return (startISO, endISO_or_None). time_str like '10:00 AM - 11:00 AM' or 'All Day'."""
    try:
        d = datetime.date.fromisoformat(date_iso)
    except Exception:
        return None, None
    t = (time_str or "").strip()
    if not t or t.lower() in ("all day", "tbd"):
        return d.isoformat(), None
    # grab up to two times
    times = re.findall(r"(\d{1,2}):(\d{2})\s*([AaPp][Mm])", t)
    def to_iso(h, m, ap):
        h = int(h); m = int(m)
        if ap.lower() == "pm" and h != 12:
            h += 12
        if ap.lower() == "am" and h == 12:
            h = 0
        return f"{date_iso}T{h:02d}:{m:02d}:00{TZ}"
    if not times:
        return d.isoformat(), None
    start = to_iso(*times[0])
    end = to_iso(*times[1]) if len(times) > 1 else None
    return start, end


def build_events():
    events = []
    end_window = TODAY + datetime.timedelta(days=WINDOW_DAYS)
    with open(SHAREABLE, newline="") as f:
        for r in csv.DictReader(f):
            if r.get("Organization", "").strip() in EXCLUDE_ORGS:
                continue
            d = r.get("Date", "").strip()
            try:
                dd = datetime.date.fromisoformat(d)
            except Exception:
                continue
            if not (TODAY <= dd <= end_window):
                continue
            start, end = parse_start(d, r.get("Time", ""))
            if not start:
                continue
            loc = r.get("Location", "").strip() or r.get("Organization", "").strip()
            ev = {
                "@type": "Event",
                "name": r.get("Event Name", "").strip(),
                "startDate": start,
                "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
                "eventStatus": "https://schema.org/EventScheduled",
                "location": {
                    "@type": "Place",
                    "name": loc,
                    "address": {
                        "@type": "PostalAddress",
                        "addressLocality": "Lake County",
                        "addressRegion": "IL",
                        "addressCountry": "US",
                    },
                },
                "isAccessibleForFree": True,
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock",
                    "url": r.get("Event URL", "").strip() or SITE,
                },
                "organizer": {
                    "@type": "Organization",
                    "name": r.get("Organization", "").strip(),
                },
                "image": SITE + "og-preview.png",
            }
            if end:
                ev["endDate"] = end
            url = r.get("Event URL", "").strip()
            if url:
                ev["url"] = url
            notes = r.get("Notes", "").strip()
            ev["description"] = (notes or f"Free family event near Grayslake, IL: {ev['name']}.")[:300]
            events.append(ev)
    events.sort(key=lambda e: e["startDate"])
    return events


def build_jsonld(events):
    website = {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": "Central Lake County Fun",
        "alternateName": "Lake County Events Calendar for Families",
        "url": SITE,
        "description": "A free, family-friendly Lake County events calendar for Grayslake, Gurnee, and nearby towns in Illinois.",
        "potentialAction": {
            "@type": "SearchAction",
            "target": {"@type": "EntryPoint", "urlTemplate": SITE + "?q={search_term_string}"},
            "query-input": "required name=search_term_string",
        },
    }
    org = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "Central Lake County Fun",
        "url": SITE,
        "logo": SITE + "favicon.svg",
        "description": "A volunteer-built guide to free and low-cost family events, parks, and outdoor fun in Lake County, Illinois.",
        "areaServed": [
            {"@type": "City", "name": "Grayslake"},
            {"@type": "City", "name": "Gurnee"},
            {"@type": "AdministrativeArea", "name": "Lake County, Illinois"},
        ],
    }
    itemlist = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "Upcoming free family events in Lake County, IL",
        "itemListOrder": "https://schema.org/ItemListOrderAscending",
        "numberOfItems": len(events),
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "item": ev}
            for i, ev in enumerate(events)
        ],
    }
    blocks = []
    for obj in (website, org, itemlist):
        blocks.append(
            '<script type="application/ld+json">'
            + json.dumps(obj, ensure_ascii=False, separators=(",", ":"))
            + "</script>"
        )
    return "\n".join(blocks)


def inject(jsonld):
    with open(INDEX, encoding="utf-8") as f:
        html = f.read()
    block = MARK_START + "\n" + jsonld + "\n" + MARK_END
    if MARK_START in html and MARK_END in html:
        html = re.sub(
            re.escape(MARK_START) + r".*?" + re.escape(MARK_END),
            block.replace("\\", "\\\\"),
            html,
            flags=re.DOTALL,
        )
    else:
        html = html.replace("</head>", block + "\n</head>", 1)
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(html)


def build_sitemap():
    lastmod = TODAY.isoformat()
    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{SITE}</loc>
    <lastmod>{lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>{SITE}built-with-ai.html</loc>
    <lastmod>{lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>{SITE}about.html</loc>
    <lastmod>{lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
</urlset>
"""
    with open(os.path.join(REPO, "sitemap.xml"), "w") as f:
        f.write(xml)


def build_robots():
    txt = f"""User-agent: *
Allow: /

Sitemap: {SITE}sitemap.xml
"""
    with open(os.path.join(REPO, "robots.txt"), "w") as f:
        f.write(txt)


if __name__ == "__main__":
    events = build_events()
    jsonld = build_jsonld(events)
    inject(jsonld)
    build_sitemap()
    build_robots()
    print(f"Injected JSON-LD with {len(events)} upcoming events (window {WINDOW_DAYS}d).")
    print("Wrote sitemap.xml and robots.txt.")
